
services:
  consul:
    image: hashicorp/consul:1.19
    volumes:
      - ./server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500" # Web UI
    networks:
      - app-network
    command: "consul agent -dev -client=0.0.0.0"
# PostgreSQL for Account Service
  account-db:
    image: postgres:13
    container_name: account-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_service_db
    volumes:
      - account-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

  # PostgreSQL for Gacha Service
  gacha-db:
    image: postgres:13
    container_name: gacha-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gacha_service_db
    volumes:
      - gacha-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

  account-service:
    build: ./account_service
    container_name: account-service
    ports:
      - "5000:5000"
    environment:
#      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@account-db:5432/account_service_db
      - JWT_SECRET_KEY=supersecretkey
      - SECRET_KEY=your_flask_secret_key
      - JWT_ALGORITHM= HS256
      - REDIS_URL=redis://redis:6379/0
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      account-db:
          condition: service_started
      consul:
        condition: service_started
    links:
      - account-db
    networks:
      - app-network

  # Gacha Service
  gacha-service:
    build:
      context: ./gacha_service
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    environment:
      - SERVICE_PORT=5001
      - DATABASE_URL=postgresql://user:password@gacha-db:5432/gacha_service_db
      - ACCOUNT_DATABASE_URL=postgresql://user:password@account-db:5432/account_service_db
      - JWT_SECRET_KEY=supersecretkey
      - SECRET_KEY=your_flask_secret_key
      - JWT_ALGORITHM= HS256
      - REDIS_URL=redis://redis:6379/0
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      redis:
        condition: service_started
      gacha-db:
        condition: service_started
      account-db:
        condition: service_started
      consul:
        condition: service_started
    links:
      - gacha-db
      - account-db
    networks:
      - app-network

  # Redis for Caching
  redis:
    image: redis:6.0-alpine
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  # Gateway (Express.js)
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:5000
      - GACHA_SERVICE_URL=http://gacha-service:5001
      - CONSUL_HOST=consul
    depends_on:
      - account-service
      - gacha-service
      - consul
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  account-db-data:
  gacha-db-data:
